#!/usr/bin/lua

local a = ("#!/usr/bin/lua\n")
local b = ('io.popen("pkill -f mako")\n')
local c = ('io.popen("lua $HOME/.config/sway/modules/alert/cmd/alert_time.lua")')

vol = io.open(".config/sway/modules/alert/alert_date_ch.lua", "w")
vol:write(a, b, c)
vol:close()
os.execute('pkill -f $HOME/.config/sway/modules/alert/alert_date.lua')
os.execute('pkill -f $HOME/.config/sway/modules/alert/alert_time.lua')
os.execute('pkill -f mako')
local n = ("font=UbuntuMono 13.5\n")
local o = ('background-color=#080815\n')
local p = ("text-color=#7F7F7F\n")
local q = ("width=400\n")
local r = ('height=300\n')
local s = ("padding=10\n")
local t = ("margin=10\n")
local u = ("progress-color=over #674FD4\n")
local v = ("layer=overlay\n")
local w = ("border-size=1\n")
local dd =("border-radius=10\n")
local x = ("border-color=#3B1515\n")
local y = ("[urgency=high]\n")
local z = ("max-icon-size=70\n")
local aa = ("default-timeout=8000\n")
local bb = ("icon-path=/usr/share/icons/Yaru-blue\n")
local cc = ("ignore-timeout=1")
str = io.open(".config/mako/config", "w")
str:write(n, o, p, q, r, s, t, u, bb, z, v, w, dd, x, aa, y, cc)
str:close()
