#!/usr/bin/lua

--kil()
local a = ("font=SF Pro Display Medium 16\n")
local b = ('background-color=#D8393900\n')
local c = ("text-color=#C4AE19\n")
local d = ("width=915\n")
local e = ('height=300\n')
local f = ("padding=10\n")
local g = ("margin=10\n")
local h = ("progress-color=over #674FD4\n")
local i = ("anchor=center\n")
local j = ("border-size=0\n")
local k = ("border-color=#5294e200\n")
local l = ("[urgency=high]\n")
local m = ("max-icon-size=70\n")
local n = ("default-timeout=8000\n")
local o = ("ignore-timeout=1")
vol = io.open(".config/mako/config", "w")
vol:write(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o)
vol:close()
local function kil() os.execute('pkill -f mako')end ; 
kil()
local  function layout() os.execute('notify-send   " "     "$(~/.config/sway/modules/tags/layouts/layout.sh)"')
return layout
end
layout()
local n = ("font=UbuntuMono 13.5\n")
local o = ('background-color=#080815\n')
local p = ("text-color=#7F7F7F\n")
local q = ("width=400\n")
local r = ('height=300\n')
local s = ("padding=10\n")
local t = ("margin=10\n")
local u = ("progress-color=over #674FD4\n")
local v = ("layer=overlay\n")
local w = ("border-size=1\n")
local dd =("border-radius=10\n")
local x = ("border-color=#3B1515\n")
local y = ("[urgency=high]\n")
local z = ("max-icon-size=70\n")
local aa = ("default-timeout=8000\n")
local bb = ("icon-path=/usr/share/icons/Yaru-blue\n")
local cc = ("ignore-timeout=1")
str = io.open(".config/mako/config", "w")
str:write(n, o, p, q, r, s, t, u, bb, z, v, w, dd, x, aa, y, cc)
str:close()
local uv = require('luv')

local function setTimeout(timeout, callback)
  local timer = uv.new_timer()
  timer:start(timeout, 0, function ()
    timer:stop()
    timer:close()
    callback()
  end)
  return timer
end
setTimeout(2000, function() kil() end)
uv.run()
